In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_excel('IMDb Movies India.xlsx')
df.head()

Movie_name    Year Duration            Genre  \
0                                         NaN      NaN            Drama   
1  #Gadhvi (He thought he was Gandhi)  2019.0  109 min            Drama   
2                         #Homecoming  2021.0   90 min   Drama, Musical   
3                             #Yaaram  2019.0  110 min  Comedy, Romance   
4                   ...And Once Again  2010.0  105 min            Drama   

   Rating  Votes            Director       Actor 1             Actor 2  \
0     NaN    NaN       J.S. Randhawa      Manmauji              Birbal   
1     7.0    8.0       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande   
2     NaN    NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur   
3     4.4   35.0          Ovais Khan       Prateik          Ishita Raj   
4     NaN    NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta   

           Actor 3  
0  Rajendra Bhatia  
1    Arvind Jangid  
2       Roy Angana  
3  Siddhant Kapoor  
4      Antara Mali

In [3]:
df.shape

(15509, 10)

In [4]:
df_cleaned = df.dropna(inplace=True)
df.isnull().sum()
df['Duration'] = df['Duration'].str.extract('(\d+)').astype(int)
df['Year'] = df['Year'].astype(float).astype(int)
df['Votes'] = df['Votes'].astype(float).astype(int)
df['Rating'] = df['Rating'].astype(float).astype(int)
df.head(100)

Movie_name  Year  Duration  \
1    #Gadhvi (He thought he was Gandhi)  2019       109   
3                               #Yaaram  2019       110   
5                  ...Aur Pyaar Ho Gaya  1997       147   
6                             ...Yahaan  2005       142   
8                    ?: A Question Mark  2012        82   
..                                  ...   ...       ...   
178                      Aa Dekhen Zara  2009       117   
179                     Aa Gale Lag Jaa  1973       148   
180                     Aa Gale Lag Jaa  1994       158   
181                        Aa Gaya Hero  2017       123   
182                       Aa Jao Please  2016       120   

                         Genre  Rating  Votes           Director  \
1                        Drama       7      8      Gaurav Bakshi   
3              Comedy, Romance       4     35         Ovais Khan   
5       Comedy, Drama, Musical       4    827       Rahul Rawail   
6          Drama, Romance, War       7   1086     Shoojit Sircar   
8    Horror, Mystery, Thriller       5    326      Allyson Patel   
..                         ...     ...    ...                ...   
178   Action, Sci-Fi, Thriller       5    866     Jehangir Surti   
179     Action, Drama, Romance       7    348     Manmohan Desai   
180           Mystery, Romance       4    115     Hamid Ali Khan   
181                     Action       2    339  Dipankar Senapati   
182                      Drama       6     16          Azad Jain   

               Actor 1                 Actor 2            Actor 3  
1         Rasika Dugal          Vivek Ghamande      Arvind Jangid  
3              Prateik              Ishita Raj    Siddhant Kapoor  
5           Bobby Deol  Aishwarya Rai Bachchan      Shammi Kapoor  
6      Jimmy Sheirgill          Minissha Lamba     Yashpal Sharma  
8            Yash Dave          Muntazir Ahmad       Kiran Bhatia  
..                 ...                     ...                ...  
178  Neil Nitin Mukesh            Bipasha Basu  Sophiya Chaudhary  
179      Shashi Kapoor         Sharmila Tagore   Shatrughan Sinha  
180      Jugal Hansraj        Urmila Matondkar       Paresh Rawal  
181            Govinda            Richa Sharma      Poonam Pandey  
182       Neha Chauhan           Ganraj Jadhav      Dipak Khetiya  

[100 rows x 10 columns]

In [5]:
features=['Year','Duration','Votes']
data = df[features].values
le = LabelEncoder()
target = le.fit_transform(df['Rating'])
le = LabelEncoder()
df['target'] = le.fit_transform(df['Rating'])
target_names = dict(zip(df['target'], df['Rating']))
df['target_names'] = df['target']
target_names = df['target_names'].to_numpy()

In [6]:
print("Features: ",features)

Features:  ['Year', 'Duration', 'Votes']


In [7]:
print("Labels: ", target_names)

Labels:  [6 3 3 ... 4 3 5]


In [8]:
data

array([[2019,  109,    8],
       [2019,  110,   35],
       [1997,  147,  827],
       ...,
       [1989,  125,   44],
       [1999,  129,  655],
       [1998,  130,   20]])

In [9]:
target

array([6, 3, 3, ..., 4, 3, 5], dtype=int64)

In [10]:
# from sklearn.metrics import classification_report

# report = classification_report(y_test, y_pred)

# # Print the classification report
# print(report)

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Assuming you have loaded your dataset into a DataFrame called 'movies_data'

# Feature selection
features = ["Duration"]
X = df[features]
y = df["Rating"]  # "Rating" as the target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a linear regression model
model = LinearRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)
y_pred
# 'y_pred' now contains the predicted "Rating" values for your test data


array([5.44485428, 5.45806517, 5.45025873, ..., 5.4458551 , 5.44085097,
       5.45666402])

In [12]:
features = ["Year", "Duration", "Votes"]
X = df[features]
y = df["Rating"]
X.columns = ["Year", "Duration", "Votes"]


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 1.8070967489478011
R-squared: 0.07488095941230777


In [13]:
df.tail()

Movie_name  Year  Duration                      Genre  Rating  \
15493           Zubaan  2015       115                      Drama       6   
15494         Zubeidaa  2001       153  Biography, Drama, History       6   
15503  Zulm Ki Zanjeer  1989       125       Action, Crime, Drama       5   
15505            Zulmi  1999       129              Action, Drama       4   
15508     Zulm-O-Sitam  1998       130              Action, Drama       6   

       Votes         Director         Actor 1          Actor 2  \
15493    408      Mozez Singh   Vicky Kaushal  Sarah Jane Dias   
15494   1496    Shyam Benegal  Karisma Kapoor            Rekha   
15503     44  S.P. Muthuraman     Chiranjeevi       Jayamalini   
15505    655       Kuku Kohli    Akshay Kumar   Twinkle Khanna   
15508     20     K.C. Bokadia      Dharmendra       Jaya Prada   

                Actor 3  target  target_names  
15493  Raaghavv Chanana       5             5  
15494    Manoj Bajpayee       5             5  
15503       Rajinikanth       4             4  
15505       Aruna Irani       3             3  
15508       Arjun Sarja       5             5

In [14]:
new_movie_features = [[1998, 130, 20]] 
predicted_rating = model.predict(new_movie_features)
print(f"Predicted Rating: {predicted_rating[0]}")

Predicted Rating: 5.385819132936


D:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
